"""Cuadd password to table Customer

Revision ID: bfe46b568911
Revises: 6dffe7b55279
Create Date: 2022-02-18 12:10:50.345365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe46b568911'
down_revision = '6dffe7b55279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'password_hash')
    # ### end Alembic commands ###
